/** Declaration file generated by dts-gen */

export = binary_data_types;

declare const binary_data_types: {
    float16: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    float16BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    float32: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    float32BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    float64: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    float64BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int16: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int16BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int2: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int24: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int24BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int32: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int32BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int4: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int40: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int40BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int48: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int48BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    int8: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt16: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt16BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt2: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt24: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt24BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt32: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt32BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt4: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt40: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt40BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt48: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt48BE: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
    uInt8: {
        be: boolean;
        bits: number;
        float: boolean;
        signed: boolean;
    };
};

